-- AlterTable
ALTER TABLE "restaurant_tables" ADD COLUMN     "color" TEXT,
ADD COLUMN     "height" DOUBLE PRECISION DEFAULT 120,
ADD COLUMN     "rotation" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "width" DOUBLE PRECISION DEFAULT 120,
ALTER COLUMN "shape" SET DEFAULT 'rect';
